env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {}
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
# https://stackoverflow.com/questions/44939304/eslint-should-be-listed-in-the-projects-dependencies-not-devdependencies
import/no-extraneous-dependencies:
  - error
  - devDependencies: true
